jdk:
- oraclejdk8

env:
  global:
  - secure: H8RweFcHUqBG1L6/ZtvAXHQcsoPxkYtnPjULgeO7fSLg7sw/J2LQ/yTQCy8ve4+NxUlBPhLgDNlaspLYO1PIowYjXcCyGJs95Jczorb+fyfT5Wryzy3EnH1M58/2NYeSVQ3SITPq15xRpIG88A277kNRMseJpFIycqGbR7yXaci4Agi9hHzEoM1K+svk5vqulOQhRUySoZaGjuQQc50I9PXGnLq97B2hAh6GomCtQcA1m70a8WB+aFi8100t7kLV/JN4BWcc4R7DojGe+SJIbWs1FOFxAdBs6YS1tlFKly0yf73o2ZgY4BY84VemZLAt+lWh584wKlkxyemkV8v7+RoFakp0qjjwpa4Vs661B4o2C37t07WOGHDhjSf+CpJEEbgtxrUkjNizEPnQnRGm448CAov5V74kMG+22PR7BdyzYym5SQsY9YbcVztNhNiOAMdT4B2xqn6RCa4zdrCYYMkVEG4WaS5VZVaRiZNO4GIIWx6KWnkhZiuddNWZXcdA/kBFut5ZxO5wcIrISdTlolaOY5kdW/Yg0tMWU2B9EaWKs48k13JRux9TgcN+7OHhGo9rz+NH9JKZJUlaTwzk6vXKGDjH0xgBEfoAaBmqURFm+/xbKmz6htbZ9AVo+ErAJQkjFkSVbzJLqtpkGw+OFwuUaPdPCwb4YOrdSIqMJfQ=
  - secure: 2lI/k+jhWpVQy49dcsLNI0IddkYlm5jKPscCpQso2l9+D7zaDuIXQAZAiHa0XeuvBnquPZhOiJ/LdOxWD4ygwrQM0bvJnrZIKONRbQ1smB9NWD1ds3iUWA7ZrTN73ExsIB+lQd5HqZOHlqOcwh9xubLea8ZFe549wYbICyfxl1kTB2PzqYmvyBXEnf+pcwYvlZAG8ngAcO6ej1qs5N0r2g5YfwEerldqRFnCxXDDV+5Neh6vjzoeZUz5XzrhPdJKqi/dXhfX7OiOxi21tRUmlabgg7irbwcWObZ+t3xaeL1x7VSTz6PtAR5+b6elZeF1KqwdXZXq8j6Ko6NHw/QVlbACy29oIq8VKJQ6bulmsdU3ORyrvIS4KPJz1FvkR0dbshweckboruvS/M+Tr2eLm9wrm87S60lxcsrsSULrrzdmfzuvt4dVYaqekpdZb5F8FmIlhAoA+sj51gnckjZbhA6KNqli8RSK4/4Y91Q0sOxsUaYgAQsAeFNYes58D/GP7NV9Onml0GKdlPv2I7793iyrUlJdym0OPsUTvWaeI3WBCiiRvLBU0s92pt1I01bQSAEg+UOAjbKk7NK7kT2+Ie38tnFuzN3t7Lgb3tKfxFxh8qC7FNGfOCmvkDh8P2gG1wXDrALw1evnZq0KxMSRo8Zb3X2931vnWIF7zXJY1vU=

script:
- mvn clean install -f pom.xml

after_success:
- chmod +x ./.travis/artifact-delete.sh
- chmod +x ./.travis/artifact-upload.sh
- "./.travis/artifact-delete.sh"
- "./.travis/artifact-upload.sh"
